services:
- type: web
  name: giavico-service
  runtime: docker
  repo: https://github.com/nnthong97/giavico_service
  plan: free
  envVars:
  - key: GIAVICO_CORS_ALLOWED_ORIGINS
    value: https://project-6d3au.vercel.app
  - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    value: org.postgresql.Driver
  - key: SPRING_DATASOURCE_PASSWORD
    sync: false
  - key: SPRING_DATASOURCE_USERNAME
    sync: false
  - key: SPRING_DATASOURCE_URL
    sync: false
  - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
    value: 5
  - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
    value: 1
  - key: OLLAMA_CONNECT_TIMEOUT
    value: PT10S
  - key: OLLAMA_TIMEOUT
    value: PT5M
  - key: OLLAMA_BASE_URL
    sync: false
  - key: OLLAMA_MODEL
    value: gemma4
  - key: SPRING_JPA_HIBERNATE_DDL_AUTO
    value: update
  region: singapore
  healthCheckPath: /actuator/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
