spring:
  application:
    name: gateway-service

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

giavico:
  cors:
    allowed-origins: ${GIAVICO_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  routes:
    formula-service-url: ${FORMULA_SERVICE_URL:http://localhost:8081}
    inventory-service-url: ${INVENTORY_SERVICE_URL:http://localhost:8082}
    chat-ai-service-url: ${CHAT_AI_SERVICE_URL:http://localhost:8083}
    rnd-document-service-url: ${RND_DOCUMENT_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
